### ISSUE TITLE
Required modules

### ISSUE THREAD

**Issue by stefandanzl** [benpate/table#1]
I didn't get the example to work because of missing import statements.
Could you add a simple `example.go` file that has all necessary dependencies as import statements with your provided example code?

**Comment by benpate** [comment]
Hey, excellent suggestion, and thanks for checkiing out `table`.  There is a lot involved in getting this set up, so a real demo would be very helpful.  I've just posted an example server in `/example` that will let you play with the widget and see how to make it go.  To use it, just go to that directory in your terminal and execute :

```bash
> go run server.go
```

The table library itself relies on a number of other tools I've built for the [Emissary](https://github.com/EmissarySocial/emissary) environment, most importantly the [rosetta Schema package](https://github.com/benpate/rosetta/tree/main/schema) which does data mapping and validation for all of the transactions, and the [form](https:/github.com/benpate/form) library that renders and validates form widgets. You'll see those configured in the demo.

I'm eager to see this work benefit others, so please let me know what your experience is -- good or bad.
